version = 0.1

[dev.global.parameters]
region = "eu-west-1"

[dev.deploy.parameters]
stack_name = "okdata-log-group-subscriber-dev"
s3_bucket = "ok-origo-dataplatform-config-dev"
s3_prefix = "deploy/okdata-log-group-subscriber"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "Stage=dev"

[prod.global.parameters]
region = "eu-west-1"

[prod.deploy.parameters]
stack_name = "okdata-log-group-subscriber-prod"
s3_bucket = "ok-origo-dataplatform-config-prod"
s3_prefix = "deploy/okdata-log-group-subscriber"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "Stage=prod"
