frameworkVersion: ">=3.19.0 <4.0.0"

service: okdata-log-group-subscriber

provider:
  name: aws
  runtime: python3.9
  memorySize: 1024
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.deploymentBucket.${self:provider.stage}, self:custom.deploymentBucket.dev}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  iam:
    role:
      permissionsBoundary: "arn:aws:iam::${aws:accountId}:policy/oslokommune/oslokommune-boundary"
      managedPolicies:
        - 'arn:aws:iam::${aws:accountId}:policy/log-group-subscriber-policy'
        - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
    VERSION: ${self:custom.version}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    STAGE: ${self:provider.stage}
    VERSION: ${self:custom.version}
    SERVICE_NAME: ${self:service}
    DESTINATION_ARN: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:service}-${self:provider.stage}-cloudwatch-event
    SUBSCRIPTION_WHITELIST: (/aws/lambda/[\w-]+)|teams-api|api-catalog-backend
    SUBSCRIPTION_BLACKLIST: -es-logs-plugin$|-cloudwatch-event$
    FILTER_PATTERN: "{ $.function_name = \"*\" }"
    ES_API_ENDPOINT: ${ssm:/dataplatform/shared/logs-elasticsearch-endpoint}
    ES_INDEX_PREFIX: dataplatform-services

package:
  patterns:
    - '!**/*'
    - log_group_subscriber/*.py

functions:
  new-log-group:
    handler: log_group_subscriber.handlers.new_log_group
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws.logs'
            detail-type:
              - 'AWS API Call via CloudTrail'
            detail:
              eventSource:
                - "logs.amazonaws.com"
              eventName:
                - "CreateLogGroup"
  cloudwatch-event:
    handler: log_group_subscriber.handlers.cloudwatch_event

plugins:
  - serverless-es-logs
  - serverless-plugin-git-variables
  - serverless-prune-plugin
  - serverless-python-requirements

resources:
  Description: |
    ${self:service} ${git:branch}:${git:sha1}
    ${git:message}

custom:
  version: 0.1.0
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    usePoetry: false
  esLogs:
    endpoint: ${ssm:/dataplatform/shared/logs-elasticsearch-endpoint}
    index: dataplatform-services
    filterPattern: '{ $.function_name = "*" }'
  prune:
    automatic: true
    number: 3
  exportGitVariables: false
  deploymentBucket:
    prod: ok-origo-dataplatform-config-prod
    dev: ok-origo-dataplatform-config-dev
